### ISSUE TITLE
运行demo

### ISSUE THREAD

**Issue by Mungeryang** [Go2Heart/EchoSight#10]
作者您好，想请问一下关于demo的app.py中"qformer_ckpt_path": "/PATH/TO/QFORMER_CHECKPOINT", "llm_ckpt":"/PATH/TO/LLM_CHECKPOINT" # Mistral-7B is the default model；所需要的文件在哪里下载呢？这周在拜读您的paper，想跑一下您的demo
![app-pymain函数](https://github.com/user-attachments/assets/4f6dc355-4e68-472c-9250-ac7adb6b5566)

**Comment by Go2Heart** [comment]
感谢您对本工作的关注，qformer_ckpt_path是训练完成后reranker ckpt的路径，llm_ckpt则是最终完成vqa的llm ckpt的路径。若想要运行demo的话，可以先使用README中提到的[reranker ckpt](https://drive.google.com/file/d/1d6QOyePuvHLlYxC1_Dvxvij3wNm3gOB9/view?usp=sharing)和[mistral llm ckpt](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2)。

**Comment by Mungeryang** [comment]
好的，感谢您的回信帮助！
