### ISSUE TITLE
NEGATIVE_DB_FILE 在哪下载呀

### ISSUE THREAD

**Issue by loushen666** [Go2Heart/EchoSight#2]
/PATH/TO/NEGATIVE_DB_FILE 这个路径的文件在哪下载

**Comment by Go2Heart** [comment]
您好，这是一份我们使用Eva-CLIP采样的一份[NEGATIVE_DB_FILE].(https://drive.google.com/file/d/1i8AzqyqG_QH0wCFHXgZzjt7tLbLWz616/view?usp=drive_link)
