### ISSUE TITLE
How to create my own Knowledge Base

### ISSUE THREAD

**Issue by LeiyuOOM** [Go2Heart/EchoSight#3]
请教一下怎么做一个自己的Knowledge Base？如何生成kb_index.faiss和kb_index_ids.pkl

**Comment by Go2Heart** [comment]
Check this [function](https://github.com/Go2Heart/EchoSight/blob/4aae05d5f063501f31c2c2f0a0187f0eb03a7188/model/retriever.py#L293).
You should prepare a knowledge base like we used (E-VQA or InfoSeek) and extract image feature (scores_path) in advance. Please ignore the arguments of image_dict and visual_attr currently.

您应该准备好像我们使用的knowledge base，和对应的image feature（scores_path）。参数image_dict和visual_attr在目前版本中可以忽视。

**Comment by LeiyuOOM** [comment]
请问如何获得image feature（scores_path）,就infoseek而言image feature（scores_path）是什么？请问能否维护一个微信群用于交流？跑通您的代码还有一些困难

**Comment by LeiyuOOM** [comment]
在app.py里第10行retriever.load_knowledge_base(knowledge_base_path) 是否缺少了scores_path参数？

**Comment by Go2Heart** [comment]
> 请问如何获得image feature（scores_path）,就infoseek而言image feature（scores_path）是什么？请问能否维护一个微信群用于交流？跑通您的代码还有一些困难

建立自己的knowledge base，image feature的提取需要自行完成，具体而言，scores_path存储的文件就是一个字典，字典的key用于存储image_url，value则是该图片的feature（如CLIP feature）。注意knowledge_base json文件中出现的image_url都需要被提取feature。Check this [function](https://github.com/Go2Heart/EchoSight/blob/4aae05d5f063501f31c2c2f0a0187f0eb03a7188/model/retriever.py#L119).

**Comment by Go2Heart** [comment]
> 在app.py里第10行retriever.load_knowledge_base(knowledge_base_path) 是否缺少了scores_path参数？

在使用load_faiss_index函数时，可以不传入scores_path，因为scores已经被存储为faiss_index文件。

**Comment by LeiyuOOM** [comment]
> > 在app.py里第10行retriever.load_knowledge_base(knowledge_base_path) 是否缺少了scores_path参数？
> 
> 在使用load_faiss_index函数时，可以不传入scores_path，因为scores已经被存储为faiss_index文件。

当我运行bash scripts/test_reranker.sh会报错，文件都已经正确下载并放在对应的文件夹
python -m test.test_reranker \
    --test_file "upload/infoseek_test_filtered.csv"\
    --knowledge_base "upload/knowledge_base/wiki_100_dict_v4.json"\
    --faiss_index "upload/faiss_index/"\
    --retriever_vit clip \
    --top_ks 1,5,10,20 \
    --retrieval_top_k 20\
    --qformer_ckpt_path "upload/reranker.pth"\
但是仍然报错：Loading knowledge base without image scores.
Loaded knowledge base with 100000 entries.
Faiss index loaded with 290448 entries.
0it [00:00, ?it/s]0 upload/images/oven_04990048.jpg
wiki_url:  https://en.wikipedia.org/wiki/Heat_engine
question:  What is the objective of this object?
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/super/anaconda3/envs/echosight/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/super/anaconda3/envs/echosight/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/super/breath_code/EchoSight-main/test/test_reranker.py", line 322, in <module>
    run_test(**test_config)
  File "/home/super/breath_code/EchoSight-main/test/test_reranker.py", line 115, in run_test
    top_k = retriever.retrieve_image_faiss(image, top_k=retrieval_top_k)
  File "/home/super/anaconda3/envs/echosight/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/super/breath_code/EchoSight-main/model/retriever.py", line 515, in retrieve_image_faiss
    D, I = self.faiss_index.search(query, top_k)
  File "/home/super/anaconda3/envs/echosight/lib/python3.10/site-packages/faiss/contrib/torch_utils.py", line 211, in torch_replacement_search
    assert d == self.d
AssertionError

**Comment by Go2Heart** [comment]
该错误是由于index中的向量维度与query向量维度的不同导致，请检查两者的维度是否一致。若您使用的是我们的knowledge base index，请把inference script中的retriever_vit参数修改为eva-clip。

**Comment by LeiyuOOM** [comment]
> image feature的提取

对于infoseek数据集，请问您有提供提取image feature，存储为scores_path代码吗（假设我下载了图片和knowledge base，而没有下载faiss_index，我该怎么利用图片和knowledge base得到faiss_index）。

**Comment by Go2Heart** [comment]
> > image feature的提取
> 
> 对于infoseek数据集，请问您有提供提取image feature，存储为scores_path代码吗（假设我下载了图片和knowledge base，而没有下载faiss_index，我该怎么利用图片和knowledge base得到faiss_index）。

依旧是使用[save_knowledge_base_faiss](https://github.com/Go2Heart/EchoSight/blob/4aae05d5f063501f31c2c2f0a0187f0eb03a7188/model/retriever.py#L396)函数。infoseek和E-VQA使用相同结构的knowledge base。

**Comment by LeiyuOOM** [comment]
> > > image feature的提取
> > 
> > 
> > 对于infoseek数据集，请问您有提供提取image feature，存储为scores_path代码吗（假设我下载了图片和knowledge base，而没有下载faiss_index，我该怎么利用图片和knowledge base得到faiss_index）。
> 
> 依旧是使用[save_knowledge_base_faiss](https://github.com/Go2Heart/EchoSight/blob/4aae05d5f063501f31c2c2f0a0187f0eb03a7188/model/retriever.py#L396)函数。infoseek和E-VQA使用相同结构的knowledge base。
对于infoseek，[save_knowledge_base_faiss](https://github.com/Go2Heart/EchoSight/blob/4aae05d5f063501f31c2c2f0a0187f0eb03a7188/model/retriever.py#L396)函数的scores_path参数传入的文件如何获得？是否有提供提取image feature并存为文件的代码。我注意到需要加载scores_path下的所有pkl文件，这些pkl文件如何获取？

**Comment by Go2Heart** [comment]
.pkl文件是我们转存的E-VQA Knowledge base的格式，具体而言就是存了一个字典(dict)对象，字典的key为image_url，value则是图片对应的embedding(clip, eva-clip, etc.)
