### ISSUE TITLE
EVQA knowledge base mismatch with wiki knowledge

### ISSUE THREAD

**Issue by dsn01** [Go2Heart/EchoSight#4]
encyclopedic_kb_wiki.json的image_url中有一部分(大约1254431张图片)没有在https://huggingface.co/datasets/TREC-AToMiC/AToMiC-Images-v0.2中出现, 请问你是重新下载了encyclopedic_kb_wiki的image_url中的内容吗

**Comment by Go2Heart** [comment]
这确实是一个被我们观察到的问题，但是鉴于该数据集是由E-VQA官方提供的repackage，因此我们没有重新下载图片，而是忽视了这些缺失的图片构建的knowledge base.
