### ISSUE TITLE
scores_path

### ISSUE THREAD

**Issue by DoggyLu** [Go2Heart/EchoSight#5]
hello，thanks for your excellent work！
I have a question about my reproduce：what is “scores_path: The path to the vision similarity score file to load.” in 'retriever.py' file?
And scores file didn't offer in the github page?????

**Comment by Go2Heart** [comment]
'scores_path' is where image scores are saved. Scores files are too large to have them provided. 
* If you are just reproducing our results on the E-VQA or InfoSeek Dataset, you can create the retriever without scores_path attributes and load the image features using the faiss index we provided. A code example is [here](https://github.com/Go2Heart/EchoSight/blob/4aae05d5f063501f31c2c2f0a0187f0eb03a7188/test/test_reranker.py#L46). 

* If you want to create your own knowledge base without knowing the construction of scores_path, you should create several scores file in python pickle. Where each pickle file should be a python dict, with keys being image identifiers(e.g. img_url) and values as the global feature embedding of Visual Encoder(e.g. CLIP).

**Comment by DoggyLu** [comment]
Thanks for your reply, it's very useful.
And I have another question when I run the test_reranker.py with infoseek.
Seems the "kb_index_ids.pkl" for infoseek dataset didn't offer?
