### ISSUE TITLE
Section retrieval accuracy & VQA accuracy

### ISSUE THREAD

**Issue by dsn01** [Go2Heart/EchoSight#6]
在论文中Table 1使用reranking的top-1准确率是36.5, 指的是wikipage的检索精度；Table 3中对应的EVQA准确率却有41.8，如何理解前者会比后者更低呢？

**Comment by Go2Heart** [comment]
即使不使用检索，直接回答E-VQA的question，也不会是0的accuracy。具体可以参考Encyclopedic VQA的paper

**Comment by dsn01** [comment]
感谢及时回复！

> 即使不使用检索，直接回答E-VQA的question，也不会是0的accuracy。具体可以参考Encyclopedic VQA的paper
