### ISSUE TITLE
--llm_checkpoint

### ISSUE THREAD

**Issue by rosarubus72** [Go2Heart/EchoSight#7]
--llm_checkpoint: The path of the Mistral or LLaMA3 checkpoint file. Where is this file obtained?

**Comment by Go2Heart** [comment]
We use checkpoints from [huggingface](https://huggingface.co/). 
Specifically: Path to the [Mistral](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2) or [LLaMA3](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) checkpoint file.

**Comment by rosarubus72** [comment]
--retrieval_results: The path of the retrieval results file. Which file is the retrieval results file?
