### ISSUE TITLE
使用VQAV2

### ISSUE THREAD

**Issue by Whhhzc** [Go2Heart/EchoSight#9]
作者您好，非常感谢您这篇文章所做出的贡献。我想请问一下 能否使用vqav2数据集来进行训练和测试呢  感谢您可以为我提供帮助！

**Comment by Go2Heart** [comment]
EchoSight是针对Knowledge-based VQA设计的，对于使用Common sense的VQA，可能不一定那么有效。当然，你也可以尝试自行构建数据集后在VQAv2上训练。

**Comment by Mungeryang** [comment]
作者您好，想请问一下关于demo的app.py中"qformer_ckpt_path": "/PATH/TO/QFORMER_CHECKPOINT", "llm_ckpt":"/PATH/TO/LLM_CHECKPOINT" # Mistral-7B is the default model；所需要的文件在哪里下载呢？这周在拜读您的paper，想跑一下您的demo
